  - name:  Database | Get acl dependency (ansible unprivileged user operations magic)
    apt: pkg="acl"
    become: yes
    tags:
      - db

  - name: Database | Create db
    postgresql_db: name={{db_name}}
    become_user: postgres
    become: yes
    tags: 
      - db

  - name: Database | Create user
    postgresql_user: name="{{db_user}}" password="{{db_password}}" role_attr_flags="{{db_user_role}}"
    become_user: postgres
    become: yes
    tags: 
      - db

