  - name: Database | Get acl dependency (ansible unprivileged user operations magic)
    ansible.builtin.apt:
      pkg: acl
    when: ansible_os_family == "Debian"
    register: acl_result
    until: acl_result is success
    retries: 10
    become: true
    tags:
      - db

  - name: Database | Create db
    community.postgresql.postgresql_db:
      name: "{{ db_name }}"
    become_user: postgres
    become: true
    tags:
      - db

  - name: Database | Create user
    community.postgresql.postgresql_user:
      name: "{{ db_user }}"
      password: "{{ db_password }}"
      role_attr_flags: "{{ db_user_role }}"
    become_user: postgres
    become: true
    tags:
      - db
