---
# tasks file for sa.postgres

  - name: Include provider related vars
    include_vars: "{{ item }}"
    with_first_found:
      - files:
          - "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml" # Debian like
          - "{{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[0] }}.yml" # Other
          - "{{ ansible_distribution }}"
          - "{{ ansible_os_family }}"
          - "main.yml"
        skip: true
    tags:
      - always

  - include_tasks: postgres.yml

  - include_tasks: postgres_remote.yml
    when: not ( docker_test is defined and ansible_os_family in ["Redhat", "CentOS"] )

  - include_tasks: db_user.yml
    when: option_create_app_user

  - include_tasks: tasks_console_helper.yml
