---
# tasks file for sa.postgres
  - include_tasks: postgres.yml

  - include_tasks: postgres_remote.yml

  - include_tasks: db_user.yml
    when: option_create_app_user

  - include_tasks: tasks_console_helper.yml
