---
  # Parameters:
  - name: PostgreSQL | Check if is installed
    command: test -x /usr/bin/psql
    register: psql_present
    changed_when: false
    ignore_errors: yes
    tags: psql

  - block:

    - name: PostgreSQL | Add GPG key to apt keyring
      apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
      register: apt_key_result
      until: apt_key_result is success
      retries: 10
      when: psql_present is failed
      tags: psql
      become: yes

    - name: PostgreSQL | Add apt repository
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
        state: present
        update_cache: yes
      tags: psql
      when: psql_present is failed
      become: yes

    - name: PostgreSQL | Install
      apt:
        pkg:
          - "postgresql-{{ postgresql_version }}"
          - libpq-dev
          - python-psycopg2
        update-cache: yes
        force: yes
        state: present
      register: package_install_result
      until: package_install_result is success
      retries: 10
      become: yes
      when: psql_present is failed
      tags: psql

    - name: PostgreSQL | Ensure Service is Started
      service: name="postgresql" state=started enabled=yes
      become: yes
      when: docker_test is not defined
      tags: psql

    when: ansible_os_family == "Debian"

  - block:

    - name: PostgreSQL | Ensure PostgreSQL deps are installed for {{ ansible_os_family }}
      package:
        name:
          - ca-certificates
          - python-psycopg2
          - python-pycurl
          - glibc-common
          - epel-release
          - libselinux-python
        state: present
      register: deps_install_result
      until: deps_install_result is success
      retries: 10
      become: yes
      tags: psql

    - name: PostgreSQL | Ensure PostgreSQL packages are installed for {{ ansible_os_family }}
      package:
        name:
          - postgresql
          - postgresql-server
          - postgresql-contrib
          - postgresql-libs
        state: present
      register: postgres_install_result
      until: postgres_install_result is success
      retries: 10
      become: yes
      tags: psql

    - name: Check if PostgreSQL database is initialized.
      stat:
        path: "{{ postgresql_data_dir }}/PG_VERSION"
      register: pgdata_dir_version
      become: yes
      tags: psql

    - name: PostgreSQL | InitDB
      shell: service postgresql initdb
      when: not pgdata_dir_version.stat.exists
      become: yes
      tags:
       - psql
       - skip_ansible_lint

    - name: PostgreSQL | Check config
      shell: chkconfig postgresql on
      become: yes
      tags:
       - psql
       - skip_ansible_lint

    - name: PostgreSQL | Ensure Service is Started
      service: name="postgresql" state=started enabled=yes
      become: yes
      when: docker_test is not defined
      tags: psql

    when: ansible_os_family != "Redhat"

