---
  - name: PostgreSQL | Install colorer grc
    package: name="grc" state="present"
    register: grc_result
    until: grc_result is success
    retries: 10
    become: yes
    tags: psql

  - name: PostgreSQL | Template colorer to current user
    template: src="{{ role_dir }}/templates/grcat.pgsql" dest="~/grcat.pgsql"
    tags: psql

  - name: PostgreSQL | psqlrc to current user
    template: src="{{ role_dir }}/templates/psqlrc.j2" dest="~/.psqlrc"
    tags: psql

  - name: PostgreSQL | Template colorer to postgres user
    template: src="{{ role_dir }}/templates/grcat.pgsql" dest="~/grcat.pgsql"
    become: yes
    become_user: postgres
    when: docker_test is not defined
    tags: psql

  - name: PostgreSQL | psqlrc to postgres user
    template: src="{{ role_dir }}/templates/psqlrc.j2" dest="~/.psqlrc"
    become: yes
    become_user: postgres
    when: docker_test is not defined
    tags: psql
