---
  - name: GRC
    when: ansible_os_family == "Debian"
    block:

    - name: PostgreSQL | Install colorer grc
      ansible.builtin.package:
        name: "grc"
        state: "present"
      register: grc_result
      until: grc_result is success
      retries: 10
      become: true
      tags: psql

    - name: PostgreSQL | Template colorer to current user
      ansible.builtin.template:
        src: "{{ role_dir }}/templates/grcat.pgsql"
        dest: "~/grcat.pgsql"
        mode: "u=rw,g=r,o="
      tags: psql

    - name: PostgreSQL | psqlrc to current user
      ansible.builtin.template:
        src: "{{ role_dir }}/templates/psqlrc.j2"
        dest: "~/.psqlrc"
        mode: "u=rw,g=r,o="
      tags: psql

    - name: PostgreSQL | Template colorer to postgres user
      ansible.builtin.template:
        src: "{{ role_dir }}/templates/grcat.pgsql"
        dest: "~/grcat.pgsql"
        mode: "u=rw,g=r,o="
      become: true
      become_user: postgres
      when: docker_test is not defined
      tags: psql

    - name: PostgreSQL | psqlrc to postgres user
      ansible.builtin.template:
        src: "{{ role_dir }}/templates/psqlrc.j2"
        dest: "~/.psqlrc"
        mode: "u=rw,g=r,o="
      become: true
      become_user: postgres
      when: docker_test is not defined
      tags: psql
