---
- hosts: www
  gather_facts: False

  vars:
    - root_dir: ..


  pre_tasks:
    - ansible.builtin.debug: msg="Pre tasks section"

    - name: ANSIBLE PYTHON | install python 2
      raw: test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)
      become: true

    - name:  UNPRIVILEGED USERS | Get acl dependency (ansible unprivileged user operations magic)
      ansible.builtin.apt: pkg="acl"
      become: true

    - name: gather facts
      setup:

  roles:
     - {
         role: "sa-postgres",
         tags: ["create", "update"],
         option_create_app_user: true,
         postgresql_listen_addresses: "*",
         db_host: localhost,
         db_user: app_user,
         db_password: app_password,
         db_name: app_database,
         db_user_role: "CREATEDB,NOSUPERUSER"
       }

  tasks:

    - ansible.builtin.debug: msg="Tasks section"
