---
- hosts: www
  gather_facts: False

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

    - name: ANSIBLE PYTHON | install python 2
      raw: test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)
      become: yes

    - name:  UNPRIVILEGED USERS | Get acl dependency (ansible unprivileged user operations magic)
      apt: pkg="acl"
      become: yes

    - name: gather facts
      setup:

  roles:
     - {
         role: "sa-postgres",
         tags: ["create", "update"],
         option_create_app_user: true,  
         db_host: localhost,
         db_user: app_user,
         db_password: app_password,
         db_name: app_database,
         db_user_role: "CREATEDB,NOSUPERUSER"
       }

  tasks:

    - debug: msg="Tasks section"



