---
# handlers file for sa.postgres

  - name: restart postgres
    ansible.builtin.service: name="{{ postgresql_service_name }}" state=started enabled=yes
    become: true
    when: docker_test is not defined
    tags:
      - psql
      - skip_ansible_lint
