---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Display pre-task message
      ansible.builtin.debug:
        msg: "Pre tasks section for {{ ansible_host }}"

    - name: Set default facts
      ansible.builtin.set_fact:
        remote_ip_address: "{{ ansible_host }}"

    - name: Include default vars
      ansible.builtin.include_vars: "playbook_vars.yml"

  roles:
      - {
        role: "sa-postgres",
        postgresql_listen_addresses: "127.0.0.1",
        postgres_force_change_peer_md5: true,
        postgres_allow_password_to_dev_network: true,
        pg_hba_properties: "{{ custom_pg_hba_properties }}"
        }
