---
- name: Prepare
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Install python for Ansible
      ansible.builtin.raw: test -e /usr/bin/python || test -e /usr/bin/python3 || (apt -y update && apt install -y python-minimal)
      become: true
      changed_when: false

    - name: Gather facts
      ansible.builtin.setup:
